name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
      - name: Create report file
        run: |
          date +%s > report.txt
          echo "Test v1.0.0" >> README.md
      - name: Commit report
        run: |
          git config --global user.name 'petroborys'
          git config --global user.email 'petroborys@gmail.com'
          git add .
          git commit -am "Automated report"
          git push
